controller_manager:
  ros__parameters:
    update_rate: 1000 # Hz

    joint_state_broadcaster_1:
      type: joint_state_broadcaster/JointStateBroadcaster
    
    ik_leg:
      type: ik_quad_foot_control/IK_Quad_Foot_Controller
    omni_control:
      type: omni_vel_controller/OmniVelController   

    pd_controller:
      type: rbt_pd_cnt/Rbt_PD_cnt


joint_state_broadcaster_1:
  ros__parameters:
    joints:
      - LF_HFE
      - LH_HFE
      - RF_HFE
      - RH_HFE
      - LF_KFE
      - LH_KFE
      - RF_KFE
      - RH_KFE
      # - LF_WHEEL_JNT
      # - LH_WHEEL_JNT
      # - RF_WHEEL_JNT
      # - RH_WHEEL_JNT
    use_sim_time: True

ik_leg:
  ros__parameters:
      homing_pos: [0.095,-0.01,0.095,-0.01,0.095,-0.01,0.095,-0.01]
      homing_dur: 5.0
      pushup_height: -0.25
      pushup_dur: 3.0
      x_pos_bound: 0.2
      z_pos_bound: 0.35
      init_feet_pos_x: -0.02375
      init_feet_pos_z: -0.25
      use_sim_time: True

omni_control:
  ros__parameters:
    mecanum_angle: 135.0
    wheel_rad: 0.03875
    pub_odom: true
    sim: true

pd_controller:
  ros__parameters:
    joint:
      - LF_HFE        # Left HIP Front
      - LF_KFE        # Left KNEE Front
      - LH_HFE        # Left HIP Back
      - LH_KFE        # Left KNEE Back
      - RF_HFE        # Right HIP Front
      - RF_KFE        # Right KNEE Front
      - RH_HFE        # Right HIP Back
      - RH_KFE        # Right KNEE Back
      # - LF_WHEEL_JNT    
      # - LH_WHEEL_JNT
      # - RF_WHEEL_JNT
      # - RH_WHEEL_JNT
 
    K_d:
      - 0.8
      - 0.8
      - 0.8
      - 0.8
      - 0.8
      - 0.8
      - 0.8
      - 0.8
      # - 0.8   # Wheel joints
      # - 0.8
      # - 0.8
      # - 0.8
      
    K_p:
      - 20.9
      - 20.9
      - 20.9
      - 20.9
      - 20.9
      - 20.9
      - 20.9
      - 20.9
      # - 0.0     # Wheel joints
      # - 0.0
      # - 0.0
      # - 0.0
 
 # Nota: Hip: 120° = 2.094 rad, Knee: 60° = 1.047 rad
    init_pos:   # NOTA! Mettere init_pos diverso da 0 
      - 2.094
      - -1.047
      - -2.094
      - 1.047
      - -2.094
      - 1.047
      - 2.094
      - -1.047
      # - 0.0   # Wheel joints
      # - 0.0
      # - 0.0
      # - 0.0
    use_sim_time: True